name: Update Docker Hub Description

on:
  push:
    branches:
      - 'main'
    paths:
      - "README.md"
      - .github/workflows/description.yml

jobs:
  update-description:
    runs-on: ubuntu-latest
    environment: DOCKER_HUB
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: plone/plone-zeo
          readme-filepath: README.md
