name: Generate Nightly Image

on:
  workflow_dispatch:
  schedule:
    - cron:  '15 22 * * *'

jobs:

  release:
    runs-on: ubuntu-latest
    environment: DOCKER_HUB

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            plone/plone-zeo
          # update label with proper version number
          labels: |
            org.label-schema.docker.cmd=docker run -d -p 8100:8100 plone/plone-zeo:nightly
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=nightly
            type=schedule,pattern=nightly-{{date 'YYYYMMDD'}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: Dockerfile.nightly
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
